[package]
name = "day05_rust"
version = "0.1.0"
edition = "2021"

[lib]
name = "day05"
path = "src/lib.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
